version: '3.4'

services:
  webapp:
    build: .
    networks:
      - streaming-analytics-example
    ports:
      - "8080:8080"

networks:
  streaming-analytics-example:
    name: streaming-analytics-example
    external: true